<a href="https://colab.research.google.com/github/BartoszTajak/Fire_Smog_Detection/blob/master/Image_recognition_GITHUB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# All libraries

In [15]:
import pandas as pd #wczyt. dancyh w f. tabelarycznym
import numpy as np #k4operacje na macierzach
import matplotlib.pyplot as plt #tworzenie wykresow
from PIL import Image, ImageDraw #wyswietlanie zdjec
import zipfile #odpakowanie pliku
from sklearn.metrics import   accuracy_score, recall_score, precision_score #metryki
from tensorflow.keras import optimizers
from tensorflow.keras.callbacks import TensorBoard
from tensorflow.keras.applications import VGG16,VGG19
from tensorflow.keras.models import Sequential
from tensorflow.keras import layers
import tensorflow as tf
import time
from matplotlib.pyplot import figure
from datetime import timedelta
from itertools import cycle
from sklearn import svm, datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import label_binarize 
from sklearn.multiclass import OneVsRestClassifier
from scipy import interp
import keras,os
from tensorflow.keras.utils import load_img , img_to_array
from keras.preprocessing.image import ImageDataGenerator
from keras.models import Model
from tensorflow import keras
from keras.layers import Input, Add, Dense, Activation, ZeroPadding2D, BatchNormalization, Flatten, Conv2D, AveragePooling2D, MaxPooling2D , Dropout , MaxPool2D
import seaborn as sns
from sklearn.metrics import matthews_corrcoef,cohen_kappa_score,roc_auc_score,classification_report,confusion_matrix , roc_curve, auc
from ipywidgets import interact, interact_manual,interactive,FileUpload, HBox, Layout,VBox
import ipywidgets as widgets

!!! pip install py7zr
!!! pip install patool
!!! pip install pyunpack

import zipfile
import scipy
from pyunpack import Archive
import patoolib
import py7zr
import uuid
import shutil
from pathlib import Path
import cv2
import io
from google.colab.patches import cv2_imshow
from tensorflow.keras.applications.resnet50 import ResNet50
from keras.initializers import glorot_uniform
import requests

from tensorflow.keras.applications.resnet50 import preprocess_input,decode_predictions
from tensorflow.keras.preprocessing import image

from google.colab import drive
drive.mount('/content/drive')


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


# Defined all variables

In [16]:

length = widgets.IntSlider(value=224,min=0,max=500,step=10,description='Image length:')
width = widgets.IntSlider(value=224,min=0,max=500,step=10,description='Image width:')
validation_split = widgets.FloatSlider(value=0.2,min=0,max=1,step=0.1,description='validation_split')
banch_size = widgets.Dropdown(options=['8', '16', '32','64','128','256'],value='32',description='banch_size:',disabled=False,)


box3 = widgets.VBox([validation_split, banch_size,length,width])
box3.layout = widgets.Layout(border="solid 3px black", margin="5px", padding="10px")

def classification_test():
  con_tree = confusion_matrix(test_labels,predicted_class_indices)
  con_tree
  sns.heatmap(con_tree, annot=True, fmt='g', cbar=False, cmap='BuPu')
  plt.show()

  clf_report = classification_report(test_labels,predicted_class_indices,labels=np.arange(3),output_dict=True)                              
  sns.heatmap(pd.DataFrame(clf_report).iloc[:-1, :].T, annot=True)
  plt.show()

path_to_save = widgets.Text(placeholder='Paste path to save',description='Save:', disabled=False )
photos_prefix = widgets.Text(placeholder='Wrire photos prefix',description='Prefix:',disabled=False)
multiplier = widgets.Dropdown(options=[1, 2, 3,4,5,6],value=2,description='Multiplier',disabled=False,) 
button_datagen_load_paameters = widgets.Button(description='load parameters')
button_images_generation = widgets.Button(description='Start generation')
rotation_range = widgets.IntSlider(value=90,min=0,max=180,step=1,description='rotation:',disabled=False,continuous_update=False,orientation='horizontal', readout=True,readout_format='d')
width_shift_range = widgets.FloatSlider(value=0.2,min=-1,max=1,step=0.1,description='width_shift_range:',disabled=False,continuous_update=False,orientation='horizontal', readout=True, readout_format='.1f',)   
height_shift_range = widgets.FloatSlider(value=0.2,min=-1,max=1,step=0.1,description='height_shift_range:',disabled=False,continuous_update=False,orientation='horizontal', readout=True, readout_format='.1f',)  
shear_range = widgets.FloatSlider(value=0,min=0,max=1,step=0.1,description='shear_range:',disabled=False,continuous_update=False,orientation='horizontal', readout=True,readout_format='.1f')     
zoom_range = widgets.FloatSlider(value=0.2,min=0,max=1,step=0.1,description='zoom_range:',disabled=False,continuous_update=False,orientation='horizontal', readout=True,readout_format='.1f')     
fill_mode = widgets.Dropdown(options=['nearest', 'reflect', 'wrap'],value='nearest',description='Fill Mode:',disabled=False,)
horizontal_flip = widgets.Dropdown(options=[True, False],value=False,description='Horizontal flip:',disabled=False,)
vertical_flip = widgets.Dropdown(options=[True, False],value=False,description='Vertical flip:',disabled=False,)



def link_pred(path_to_images):
  file=os.listdir(path_to_images)
  print('Number of files in the folder =', len(file))


slow = interactive(link_pred,path_to_images = widgets.Text( value='/content/drive/MyDrive/', description='Path:',disabled=False,  ) )
datagen_parameters = widgets.VBox([rotation_range, width_shift_range,height_shift_range,shear_range,zoom_range,fill_mode,photos_prefix,multiplier,button_datagen_load_paameters,button_images_generation])
path_to_load_and_save = VBox(children=[slow,path_to_save])

def main_start(_): 
  path = path_to_load_and_save.children[0].kwargs_widgets[0].value+'/'
  parameters = [rotation_range.value,width_shift_range.value,height_shift_range.value,shear_range.value,zoom_range.value,horizontal_flip.value,vertical_flip.value,fill_mode.value,photos_prefix.value,multiplier.value]
  photos(path,parameters)

button_images_generation.on_click(main_start)

box1 = widgets.VBox(children=[slow,path_to_save])
box2 = widgets.VBox([slow,rotation_range, width_shift_range,height_shift_range,shear_range,zoom_range,fill_mode,photos_prefix,multiplier,horizontal_flip,vertical_flip,button_images_generation])
box1.layout = widgets.Layout(border="solid 5px black", margin="5px", padding="20px")
box2.layout = widgets.Layout(border="solid 5px black", margin="5px", padding="30px")




#All models created before

ResNet50_Adam_32 = 'ResNet50,Adam_Optymalizer_BanchSize32'
ResNet50_RMS_64 = 'ResNet50,RMS_Optymalizer_BanchSize64'
VGG16_Adam_32 = 'VGG16,Adam_Optymalizer_BanchSize32'
VGG16_RMS_64 = 'VGG16,RMS_Optymalizer_BanchSize64'
Xception_Adam_32 = 'Xceptionl,Adam_Optymalizer_BanchSize32'
Xception_RMS_64 = 'Xception,RMS_Optymalizer_BanchSize64'

saved_models = widgets.Dropdown(options=[ResNet50_Adam_32, ResNet50_RMS_64, VGG16_Adam_32,VGG16_RMS_64,Xception_Adam_32,Xception_RMS_64],value=ResNet50_Adam_32,description='Choose Model:',disabled=False,)



def load_saved_model(b):
  global model
  main_path = '/content/drive/MyDrive/KERAS/Models/'
  print(main_path+saved_models.value)
  model = tf.keras.models.load_model(main_path+saved_models.value)
  print('model loaded')
  return model



button_model_load = widgets.Button(description='Load model')
button_model_load.on_click(load_saved_model)

box4 = widgets.VBox([saved_models,button_model_load])
box4.layout = widgets.Layout(border="solid 3px black", margin="5px", padding="10px")

# Section to Images generation

In [ ]:
class photos():
  '''Class for generating images using Keras preprocessing  ImageDataGenerator.'''
   

  def __init__(self,path,*parameters):
    self.path = path
    self.parameters = parameters[0]
    # print(self.parameters)
    self.path = path
    self.dic = [i for i in os.listdir(self.path) if ('7z'  in i) or ('rar'  in i) or ('zip'  in i)]
    self.unpacking()
    self.parameters = parameters[0]
    self.datagen_load_paameters()
    self.images_generation()
    self.path = path
    self.dic_packing = [i for i in os.listdir(self.path)]
    self.packing()
    print('Program Done!!!')

  def unpacking(self):  
    print('Unpacking...')  
    for file in self.dic:
      os.makedirs(self.path+'/'+file.split('.')[0])
      if 'zip' in file:
          with zipfile.ZipFile(self.path + "/" + file, 'r') as zip_ref:
              zip_ref.extractall(self.path+'/'+file.split('.')[0])
      if '7z' in file:
          Archive(self.path + "/" + file ).extractall(self.path+'/'+file.split('.')[0])
      if 'rar' in file:
          patoolib.extract_archive(self.path+'/'+file, outdir=self.path+'/'+file.split('.')[0])

      os.remove(self.path + "/" + file)


  def datagen_load_paameters(self):
    datagen = ImageDataGenerator(
      rotation_range=self.parameters[0],
      width_shift_range=self.parameters[1],
      height_shift_range=self.parameters[2],
      rescale=1./255,
      shear_range=self.parameters[3],
      zoom_range=self.parameters[4],
      horizontal_flip=self.parameters[5],
      vertical_flip=self.parameters[6],
      fill_mode=self.parameters[7])
    print('Parameters loaded\n' , 'Start generation ')
    return datagen
  



  def images_generation(self):

    print('Image generation...')
    datagen = self.datagen_load_paameters()
    print(datagen.fill_mode)
    for i in self.dic:
      path = self.path +''+ i.split('.')[0]
      
      print(path)
      arr = os.listdir(path)
      print(arr)
      for i in arr:
        pic = load_img(path+'/'+i)
        pic_array = img_to_array(pic)
        X = pic_array.reshape((1,) + pic_array.shape)

        count = 0
        for batch in datagen.flow(X, batch_size=1,save_to_dir=path, save_prefix=self.parameters[8], save_format='jpg'):
            count += 1
            if count > int(self.parameters[9])-1:
                break
    


  def packing(self):    
      print('start packing')
      for i in self.dic_packing:
        archive= py7zr.SevenZipFile(self.path  + i +'.7z', 'w')
        archive.writeall(self.path + i,'base' )
        archive.close()
      dic = [i for i in os.listdir(self.path) if ('7z'  not in i)]
      for i in dic :
        shutil.rmtree(self.path  + i)
      print('Deleting old files')
  def __call__(self):

    return f'PATH :{self.path} ' , f'PARAMETERS : {self.parameters}'




***`Images generation - How to use`***

---




1.   Paste a path with the source (zipped files like .zip .rar .7z ) on your   Google drive , like : '/content/drive/MyDrive/KERAS'
2.   Fill all parameters 
3.   Click the button "Start Generator"
4.   After all one can download files from the same folder.











---



In [17]:
widgets.HBox([box2])

# Main section to estimate

In [18]:
# loading model
widgets.HBox([box4])

/content/drive/MyDrive/KERAS/Models/Xceptionl,Adam_Optymalizer_BanchSize32
model loaded


In [19]:
# widget to set value for variables
widgets.HBox([box3])

In [ ]:
# uploadind our sets and put in temp folder

PATH_FIRE = '/content/drive/MyDrive/KERAS/Dataset/Fire.zip'
PATH_Smoke = '/content/drive/MyDrive/KERAS/Dataset/Smoke.zip'
PATH_Normal = '/content/drive/MyDrive/KERAS/Dataset/Normal.zip'

zip_ref = zipfile.ZipFile(PATH_FIRE,'r')
zip_ref.extractall('/tmp')
zip_ref.close()

zip_ref = zipfile.ZipFile(PATH_Smoke,'r')
zip_ref.extractall('/tmp')
zip_ref.close()

zip_ref = zipfile.ZipFile(PATH_Normal,'r')
zip_ref.extractall('/tmp')
zip_ref.close()



In [ ]:
# defining classes , split set into   test and training ...

train_datagen = ImageDataGenerator(
    rescale=1./255,
    horizontal_flip=True,
    validation_split=validation_split.value) # set validation split


validation_datagen = ImageDataGenerator(
    rescale=1/255,
        horizontal_flip=True,)

train_generator = train_datagen.flow_from_directory(
    '/tmp',
    target_size=(length.value, width.value),
    batch_size=int(banch_size.value),
    classes = ['Fire' , 'Smoke' , 'Normal'],
    class_mode='categorical',
    shuffle=True ,
    subset="training") # set as training data

validation_generator = train_datagen.flow_from_directory(
    '/tmp',
    target_size=(length.value, width.value),
    classes = ['Fire' , 'Smoke' , 'Normal'],
    batch_size=int(banch_size.value),
    class_mode='categorical',
    shuffle=False ,
    subset='validation') # set as validation data


In [ ]:

pred=model.predict_generator(validation_generator)

predicted_class_indices=np.argmax(pred,axis=1)
predicted_class_indices

labels = (train_generator.class_indices)
labels = dict((v,k) for k,v in labels.items())
predictions = [labels[k] for k in predicted_class_indices]

# validation_generator.labels = klasy ze zbioru testowego 
test_labels = validation_generator.labels

# heatmap to results visualization
classification_test()




In [23]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 xception (Functional)       (None, 2048)              20861480  
                                                                 
 flatten (Flatten)           (None, 2048)              0         
                                                                 
 dense (Dense)               (None, 6000)              12294000  
                                                                 
 dropout (Dropout)           (None, 6000)              0         
                                                                 
 batch_normalization_4 (Batc  (None, 6000)             24000     
 hNormalization)                                                 
                                                                 
 dense_1 (Dense)             (None, 5000)              30005000  
                                                        

# Comparison of models

In [20]:
def convert (df):
  accuracy = df['accuracy'].tolist()
  accuracy = accuracy[0].replace('[','')
  accuracy = accuracy.replace(']','')
  accuracy = [float(i) for i in accuracy.split(',')]
  return accuracy

### Xception_model , Optamalizer Adam  ,Banch Size = 32 , Input_Shape 224x224 
df = pd.read_csv('/content/drive/MyDrive/KERAS/Models/Xceptionl,Adam_Optymalizer_BanchSize32/Xception_results_vol2.csv',sep= ';')
accuracy_Xception = convert (df)
accuracy_TEST_SET_Xception = 0.9396059657521635

### VGG_model, Optamalizer Adam   ,Banch Size = 32 , Input_Shape 224x224
df = pd.read_csv('/content/drive/MyDrive/KERAS/Models/VGG16,Adam_Optymalizer_BanchSize32/VGG16_results1_vol2.csv',sep= ';')
accuracy_VGG = convert (df)
accuracy_TEST_SET_VGG = 0.8576689375805561

### Resnet_model , Optamalizer Adam   ,Banch Size = 32 , Input_Shape 224x224
df = pd.read_csv('/content/drive/MyDrive/KERAS/Models/ResNet50,Adam_Optymalizer_BanchSize32/VGG16_results1_vol2.csv',sep= ';')
accuracy_Resnet = convert (df)
accuracy_TEST_SET_RESNET = 0.7541889154851776


# ### Xception_model , Optamalizer RMS  ,Banch Size = 64 , Input_Shape 224x224 
df = pd.read_csv('/content/drive/MyDrive/KERAS/Models/Xception,RMS_Optymalizer_BanchSize64/xCEPTION_results1_vol2.csv',sep= ';')
accuracy_Xception_Vol01 = convert (df)
accuracy_TEST_SET_Xception_Vol01 = 0.900202540968514

# ### VGG_model , Optamalizer RMS  ,Banch Size = 64 , Input_Shape 224x224 
df = pd.read_csv('/content/drive/MyDrive/KERAS/Models/VGG16,RMS_Optymalizer_BanchSize64/VGG16_results1_vol2.csv',sep= ';')
accuracy_VGG_Vol01 = convert (df)
accuracy_TEST_SET_VGG_Vol01 = 0.8112686429755109

# ### Resnet_model , Optamalizer RMS  ,Banch Size = 64 , Input_Shape 224x224 
df = pd.read_csv('/content/drive/MyDrive/KERAS/Models/ResNet50,RMS_Optymalizer_BanchSize64/Resnet_results1_vol2.csv',sep= ';')
accuracy_Resnet_Vol01 = convert (df)
accuracy_TEST_SET_ResNet_Vol01 = 0.518320751242865






In [21]:
def models_compare(Xception,VGG,ResNet,grid,ee):

    x_Xception = 0 if Xception == 'off' else Xception
    x_VGG = 0 if VGG == 'off' else VGG
    x_ResNet = 0 if ResNet == 'off' else ResNet

    fig , (ax_1 , ax_2) = plt.subplots(1,2,figsize=(22,10))
    ax_1.set_title('Optamalizer Adam ,Banch Size = 32 , Input_Shape 224x224')
    ax_1.plot(accuracy_Xception,label='Xception',color= 'r',linewidth=x_Xception)
    ax_1.plot(accuracy_VGG,label='VGG16',color= 'blue',linewidth=x_VGG)
    ax_1.plot(accuracy_Resnet,label='ResNet', color= 'green',linewidth=x_ResNet)
    ax_1.grid(grid)
    ax_1.set_ylabel('Accuracy',fontsize = 15)
    ax_1.set_xlabel('Epochs',fontsize = 15)

    models_list = [x_Xception,x_VGG,x_ResNet]
    labels_desciption =['Xception TEST_SET ','VGG16 TEST_SET ','Resnet TEST_SET ']
    color_list = ['r','blue','green']
    accuracy_list = [accuracy_TEST_SET_Xception,accuracy_TEST_SET_VGG,accuracy_TEST_SET_RESNET]
    accuracy_list_vol1 = [accuracy_TEST_SET_Xception_Vol01,accuracy_TEST_SET_VGG_Vol01,accuracy_TEST_SET_ResNet_Vol01]

    for model,desciption,color,accuracy in zip(models_list,labels_desciption,color_list,accuracy_list):

      ax_1.axhline(y=accuracy, color= color, linestyle='--',label=desciption,linewidth=model)
      ax_1.text(ee[0]+2, accuracy+0.007, f'Accuracy_TEST_SET = {round(accuracy,2)}',color= color,alpha=float(model))


    ax_1.legend( ('Xception', 'VGG16', 'ResNet'), loc='lower right', shadow=True, fancybox=True)
    ax_1.set_xlim([ee[0], ee[1]])



    ax_2.set_title('Optamalizer RMS  ,Banch Size = 64 , Input_Shape 224x224')
    ax_2.plot(accuracy_Xception_Vol01,color= 'r',linewidth=x_Xception)
    ax_2.plot(accuracy_VGG_Vol01,color= 'blue',linewidth=x_VGG)
    ax_2.plot(accuracy_Resnet_Vol01,color= 'green',linewidth=x_ResNet)


    for model,desciption,color,accuracy in zip(models_list,labels_desciption,color_list,accuracy_list_vol1):

          ax_2.axhline(y=accuracy, color= color, linestyle='--',label= desciption,linewidth=model)
          ax_2.text(ee[0]+2, accuracy+0.007, f'Accuracy_TEST_SET = {round(accuracy,2)}',color= color,alpha=float(model))



    ax_2.legend( ('Xception', 'VGG16', 'ResNet'), loc='lower right', shadow=True, fancybox=True)
    ax_2.grid(grid)
    ax_2.set_ylabel('Accuracy',fontsize = 15)
    ax_2.set_xlabel('Epochs',fontsize = 15)
    ax_2.set_xlim([ee[0], ee[1]])
    plt.show()


In [22]:
www=interactive(models_compare, Xception=['off', '1', '2', '3'],VGG=['off', '1', '2', '3'],ResNet=['off', '1', '2', '3'],grid=True,
                ee= widgets.IntRangeSlider(value=[0,50],min=0,max=50,step=1,description='Epochs:')
                
                       )
controls = HBox(children=[www], layout = Layout(flex_flow='initial'))

display(VBox([controls]))

# Creating and save models 

In [ ]:
VGG16_model = tf.keras.applications.VGG16(include_top=False,pooling='avg',classes=3,weights='imagenet')
ResNet50_model = tf.keras.applications.ResNet50(include_top=False,pooling='avg',classes=3,weights='imagenet')
Xception_model = tf.keras.applications.Xception(include_top=False,pooling='avg',classes=3,weights='imagenet')

model_from_lista = [ResNet50_model,VGG16_model,Xception_model]
models = ['ResNet50_model','VGG16_model']
def Modele():

  model = Sequential()
  model.add(Xception_model)
  model.layers[0].trainable = False
  model.add(Flatten())
  model.add(Dense(units=6000,activation="relu"))
  model.add(Dropout(0.5))
  model.add(BatchNormalization())
  model.add(Dense(units=5000,activation="relu")) 
  model.add(Dropout(0.4))
  model.add(BatchNormalization())
  model.add(Dense(units=4000,activation="relu"))
  model.add(Dropout(0.3))
  model.add(BatchNormalization())
  model.add(Dense(units=2000,activation="relu"))
  model.add(Dropout(0.2))
  model.add(Dense(units=1000,activation="relu"))
  model.add(Dropout(0.1))
  model.add(Dense(units=100,activation="relu"))
  model.add(Dense(units=3, activation="softmax"))
  return model


In [ ]:
# VGG19 Model
model = Sequential()
model.add(Conv2D(input_shape=(224,224,3),filters=64,kernel_size=(3,3),padding="same", activation="relu"))
model.add(Conv2D(filters=64,kernel_size=(3,3),padding="same", activation="relu"))
model.add(MaxPool2D(pool_size=(2,2),strides=(2,2)))
model.add(Conv2D(filters=128, kernel_size=(3,3), padding="same", activation="relu"))
model.add(Conv2D(filters=128, kernel_size=(3,3), padding="same", activation="relu"))
model.add(MaxPool2D(pool_size=(2,2),strides=(2,2)))
model.add(Conv2D(filters=256, kernel_size=(3,3), padding="same", activation="relu"))
model.add(Conv2D(filters=256, kernel_size=(3,3), padding="same", activation="relu"))
model.add(Conv2D(filters=256, kernel_size=(3,3), padding="same", activation="relu"))
model.add(MaxPool2D(pool_size=(2,2),strides=(2,2)))
model.add(Conv2D(filters=512, kernel_size=(3,3), padding="same", activation="relu"))
model.add(Conv2D(filters=512, kernel_size=(3,3), padding="same", activation="relu"))
model.add(Conv2D(filters=512, kernel_size=(3,3), padding="same", activation="relu"))
model.add(MaxPool2D(pool_size=(2,2),strides=(2,2)))
model.add(Conv2D(filters=512, kernel_size=(3,3), padding="same", activation="relu"))
model.add(Conv2D(filters=512, kernel_size=(3,3), padding="same", activation="relu"))
model.add(Conv2D(filters=512, kernel_size=(3,3), padding="same", activation="relu"))
model.add(MaxPool2D(pool_size=(2,2),strides=(2,2)))
model.add(Flatten())
model.add(Dense(units=6000,activation="relu"))
model.add(Dropout(0.5))
model.add(BatchNormalization())
model.add(Dense(units=5000,activation="relu"))
model.add(Dropout(0.4))
model.add(BatchNormalization())
model.add(Dense(units=4000,activation="relu"))
model.add(Dropout(0.3))
model.add(BatchNormalization())
model.add(Dense(units=3000,activation="relu"))
model.add(Dropout(0.2))
model.add(BatchNormalization())
model.add(Dense(units=2000,activation="relu"))
model.add(Dropout(0.1))
model.add(Dense(units=100,activation="relu"))
model.add(Dense(units=3, activation="softmax"))

model.compile(optimizer = tf.optimizers.Adam(learning_rate=1e-5),loss = 'binary_crossentropy', metrics=['accuracy'])   
history = model.fit(train_generator,epochs = 40)
model.save(fr'...') 

In [ ]:
# Resnet Model

def identity_block(X, f, filters, stage, block):
    # defining name basis
    conv_name_base = 'res' + str(stage) + block + '_branch'
    bn_name_base = 'bn' + str(stage) + block + '_branch'

    # Retrieve Filters
    F1, F2, F3 = filters

    # Save the input value. We'll need this later to add back to the main path. 
    X_shortcut = X

    # First component of main path
    X = Conv2D(filters = F1, kernel_size = (1, 1), strides = (1,1), padding = 'valid', name = conv_name_base + '2a', kernel_initializer = glorot_uniform(seed=0))(X)
    X = BatchNormalization(axis = 3, name = bn_name_base + '2a')(X)
    X = Activation('relu')(X)

    # Second component of main path
    X = Conv2D(filters = F2, kernel_size = (f, f), strides = (1,1), padding = 'same', name = conv_name_base + '2b', kernel_initializer = glorot_uniform(seed=0))(X)
    X = BatchNormalization(axis = 3, name = bn_name_base + '2b')(X)
    X = Activation('relu')(X)

    # Third component of main path
    X = Conv2D(filters = F3, kernel_size = (1, 1), strides = (1,1), padding = 'valid', name = conv_name_base + '2c', kernel_initializer = glorot_uniform(seed=0))(X)
    X = BatchNormalization(axis = 3, name = bn_name_base + '2c')(X)

    # Final step: Add shortcut value to main path, and pass it through a RELU activation
    X = Add()([X, X_shortcut])
    X = Activation('relu')(X)

    return X

def convolutional_block(X, f, filters, stage, block, s = 2):
  # defining name basis
  conv_name_base = 'res' + str(stage) + block + '_branch'
  bn_name_base = 'bn' + str(stage) + block + '_branch'
  
  # Retrieve Filters
  F1, F2, F3 = filters
  
  # Save the input value
  X_shortcut = X


  ##### MAIN PATH #####
  # First component of main path 
  X = Conv2D(F1, (1, 1), strides = (s,s), name = conv_name_base + '2a', kernel_initializer = glorot_uniform(seed=0))(X)
  X = BatchNormalization(axis = 3, name = bn_name_base + '2a')(X)
  X = Activation('relu')(X)

  # Second component of main path
  X = Conv2D(filters=F2, kernel_size=(f, f), strides=(1, 1), padding='same', name=conv_name_base + '2b', kernel_initializer=glorot_uniform(seed=0))(X)
  X = BatchNormalization(axis=3, name=bn_name_base + '2b')(X)
  X = Activation('relu')(X)

  # Third component of main path
  X = Conv2D(filters=F3, kernel_size=(1, 1), strides=(1, 1), padding='valid', name=conv_name_base + '2c', kernel_initializer=glorot_uniform(seed=0))(X)
  X = BatchNormalization(axis=3, name=bn_name_base + '2c')(X)

  
  ##### SHORTCUT PATH ####
  X_shortcut = Conv2D(F3, (1, 1), strides = (s,s), name = conv_name_base + '1', kernel_initializer = glorot_uniform(seed=0))(X_shortcut)
  X_shortcut = BatchNormalization(axis = 3, name = bn_name_base + '1')(X_shortcut)

  # Final step: Add shortcut value to main path, and pass it through a RELU activation
  X = Add()([X, X_shortcut])
  X = Activation('relu')(X)
  
  return X

def ResNet50(input_shape = (224, 224, 3), classes = 3):   
    # Define the input as a tensor with shape input_shape
    X_input = Input(input_shape)

    # Zero-Padding
    X = ZeroPadding2D((3, 3))(X_input)
    
    # Stage 1
    X = Conv2D(64, (7, 7), strides = (2, 2), name = 'conv1', kernel_initializer = glorot_uniform(seed=0))(X)
    X = BatchNormalization(axis = 3, name = 'bn_conv1')(X)
    X = Activation('relu')(X)
    X = MaxPooling2D((3, 3), strides=(2, 2))(X)

    # Stage 2
    X = convolutional_block(X, f = 3, filters = [64, 64, 256], stage = 2, block='a', s = 1)
    X = identity_block(X, 3, [64, 64, 256], stage=2, block='b')
    X = identity_block(X, 3, [64, 64, 256], stage=2, block='c')

    # Stage 3
    X = convolutional_block(X, f = 3, filters = [128, 128, 512], stage = 3, block='a', s = 2)
    X = identity_block(X, 3, [128, 128, 512], stage=3, block='b')
    X = identity_block(X, 3, [128, 128, 512], stage=3, block='c')
    X = identity_block(X, 3, [128, 128, 512], stage=3, block='d')

    # Stage 4
    X = convolutional_block(X, f = 3, filters = [256, 256, 1024], stage = 4, block='a', s = 2)
    X = identity_block(X, 3, [256, 256, 1024], stage=4, block='b')
    X = identity_block(X, 3, [256, 256, 1024], stage=4, block='c')
    X = identity_block(X, 3, [256, 256, 1024], stage=4, block='d')
    X = identity_block(X, 3, [256, 256, 1024], stage=4, block='e')
    X = identity_block(X, 3, [256, 256, 1024], stage=4, block='f')

    # Stage 5
    X = convolutional_block(X, f = 3, filters = [512, 512, 2048], stage = 5, block='a', s = 2)
    X = identity_block(X, 3, [512, 512, 2048], stage=5, block='b')
    X = identity_block(X, 3, [512, 512, 2048], stage=5, block='c')

    # AVGPOOL.
    X = AveragePooling2D((2, 2), name='avg_pool')(X)

    # output layer
    X = Flatten()(X)
    X = Dense(classes, activation='softmax', name='fc' + str(classes), kernel_initializer = glorot_uniform(seed=0))(X)
    
    # Create model
    model = Model(inputs = X_input, outputs = X, name='ResNet50')

    return model

model = ResNet50(input_shape = (224, 224, 3), classes = 3)

In [ ]:

model.compile(optimizer = tf.optimizers.Adam(learning_rate=1e-5),loss = 'binary_crossentropy', metrics=['accuracy'])   
history = model.fit(train_generator,epochs = 50)
model.save(fr'...') 

# Detecting fire on a random picture

In [31]:
uploader = widgets.FileUpload(multiple=True)

def on_upload_change(change):
  for name, file_info in uploader.value.items():
      with open (f'/content/drive/MyDrive/KERAS/upload_photo/{name}', 'wb') as file:
            file.write(file_info['content'])
            uploader.close_all

uploader.observe(on_upload_change, names='_counter')

button = widgets.Button(description='Remove files ')
# out = widgets.Output()
def remove(_):
          screen_path = os.listdir('/content/drive/MyDrive/KERAS/upload_photo')
          for i in screen_path:
              os.remove('/content/drive/MyDrive/KERAS/upload_photo/'+i)

# linking button and function together using a button's method
button.on_click(remove)

button_pred = widgets.Button(description='Predict ')
def predict(_):
  train_datagen = ImageDataGenerator(rescale=1/255)
  validation_datagen = ImageDataGenerator(rescale=1/255)

  validation_generator = validation_datagen.flow_from_directory(
          '/content/drive/MyDrive/KERAS/',  # This is the source directory for training images
          
          classes = ['upload_photo'],
          target_size=(224, 224),  # All images will be resized to 200x200
          batch_size = 1,
          # Use binary labels
          class_mode='categorical',    
          shuffle=False)


  pred=model.predict_generator(validation_generator , verbose=0)
  predicted_class_indices=np.argmax(pred,axis=1)

  labels = {'FIRE': 0, 'SMOKE': 1, 'NORMAL' :2}
  labels = dict((v,k) for k,v in labels.items())
  predictions = [labels[k] for k in predicted_class_indices]
  print(pred)
  print(predictions)

button_pred.on_click(predict)

www= widgets.Text(
    
    placeholder='paste link with image',
    description='String:',
    disabled=False
)

button_link = widgets.Button(description='load from link')
# out = widgets.Output()
def link_pred(_):
  r = requests.get(www.value)

  with open ('/content/drive/MyDrive/KERAS/upload_photo/pictuje.jpg','wb') as f:
    f.write(r.content)

# linking button and function together using a button's method
button_link.on_click(link_pred)


widgets.HBox([uploader, button,button_pred,www,button_link])

Found 1 images belonging to 1 classes.


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:37: UserWarning: `Model.predict_generator` is deprecated and will be removed in a future version. Please use `Model.predict`, which supports generators.


[[1.0000000e+00 2.6670014e-12 1.2477237e-08]]
['FIRE']
Found 7 images belonging to 1 classes.


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:37: UserWarning: `Model.predict_generator` is deprecated and will be removed in a future version. Please use `Model.predict`, which supports generators.


[[1.0000000e+00 6.6468760e-13 4.5115832e-13]
 [1.0000000e+00 6.6468760e-13 4.5115832e-13]
 [9.7409850e-01 8.2879684e-05 2.5818536e-02]
 [1.0000000e+00 2.7731389e-18 9.0810559e-18]
 [1.0000000e+00 2.6544119e-11 3.7868772e-10]
 [1.0000000e+00 7.6465820e-17 4.7368945e-15]
 [1.0000000e+00 7.6465820e-17 4.7368945e-15]]
['FIRE', 'FIRE', 'FIRE', 'FIRE', 'FIRE', 'FIRE', 'FIRE']
